CREATE TABLE CAR_INFO (
	MODEL_NUM INT AUTO_INCREMENT PRIMARY KEY
	, MODEL_NAME VARCHAR(50) NOT NULL
	, PRICE INT NOT NULL
	, BRAND VARCHAR(30) NOT NULL
);

CREATE TABLE SALES_INFO (
	SALES_NUMBER INT AUTO_INCREMENT PRIMARY KEY
	,	BUYER VARCHAR(30) NOT NULL
	,	TEL VARCHAR(50)
	,	COLOR VARCHAR(30) NOT NULL
	,	SALES_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	,	MODEL_NUM INT NOT NULL REFERENCES CAR_INFO (MODEL_NUM)
);

DROP TABLE sales_info;

SELECT * FROM car_info;
SELECT * FROM sales_info;

INSERT INTO car_info (MODEL_NAME, PRICE ,BRAND) VALUES ('아반떼', 10000 ,'현대');
INSERT INTO sales_info 
(BUYER,  TEL, COLOR, MODEL_NUM) 
VALUES
('정몽규','010-1111-1111' ,'블랙', 2);


SELECT SALES_NUMBER
   , BUYER
   , TEL
   , SALES_DATE
   , COLOR
   , c.MODEL_NAME
   , c.PRICE
FROM CAR_INFO c, sales_info s
WHERE c.MODEL_NUM = s.MODEL_NUM;


DELETE FROM sales_info 
WHERE SALES_NUMBER > 4;

