-- 1번 문제
CREATE TABLE MY_MEMBER (
	MEM_NUM INT PRIMARY KEY,
	MEM_ID VARCHAR(30),
	MEM_PW VARCHAR(30),
	MEM_NAME VARCHAR(30),
	MEM_AGE INT NOT NULL,
	MEM_EMAIL VARCHAR(30) NOT NULL
);
SELECT * FROM my_member;


INSERT INTO MY_MEMBER (MEM_NUM, MEM_ID, MEM_PW, MEM_NAME, MEM_AGE, MEM_EMAIL)
VALUES (1, 'a', 'a1', '에이', 1, 'a@naver.com');