-- 1번 문제
CREATE TABLE MY_MEMBER (
	MEM_NUM INT PRIMARY KEY,
	MEM_ID VARCHAR(30) NOT NULL,
	MEM_PW VARCHAR(30) NOT NULL,
	MEM_NAME VARCHAR(30) NOT NULL,
	MEM_AGE INT,
	MEM_EMAIL VARCHAR(30) 
);
SELECT * FROM my_member;

-- 2번 문제
INSERT INTO MY_MEMBER (MEM_NUM, MEM_ID, MEM_PW, MEM_NAME, MEM_AGE, MEM_EMAIL)
VALUES (1, 'a', 'a1', '에이', 1, 'a@naver.com');
INSERT INTO MY_MEMBER (MEM_NUM, MEM_ID, MEM_PW, MEM_NAME, MEM_AGE, MEM_EMAIL)
VALUES (2, 'b', 'b1', '비', 2, 'b@naver.com');
INSERT INTO MY_MEMBER (MEM_NUM, MEM_ID, MEM_PW, MEM_NAME, MEM_AGE, MEM_EMAIL)
VALUES (3, 'c', 'c1', '씨', 3, 'c@naver.com');

DELETE FROM my_member;

-- 3번 문제
UPDATE my_member SET 
	MEM_NAME = '김자바'
	,	MEM_ID = 'KIMJAVA'
WHERE MEM_NUM = 1;

-- 4번문제
SELECT * FROM emp;
SELECT EMPNO, ENAME, SAL, COMM
FROM emp
WHERE SAL >= 500 AND SAL <= 3000 AND COMM IS NOT NULL;

-- 5번 문제
SELECT EMPNO, ENAME, HIREDATE
FROM emp
WHERE ENAME LIKE '%기'
OR ENAME LIKE '%김%'
ORDER BY EMPNO DESC;

-- 6번 문제
SELECT 
    EMPNO, 
    ENAME, 
    DEPTNO, 
    CASE 
        WHEN DEPTNO = 10 THEN '인사부'
        WHEN DEPTNO = 20 THEN '영업부'
        WHEN DEPTNO = 30 THEN '개발부'
        ELSE '생산부'
    END AS DEPTNAME
FROM emp;

-- 7번 문제
SELECT EMPNO, ENAME, HIREDATE, IFNULL(COMM, 0)
FROM emp
WHERE MONTH(HIREDATE) = 1 
ORDER BY HIREDATE ASC;

-- 8번 문제
SELECT SUM(SAL) AS '급여의 합', AVG(SAL) AS '급여의 평균', IFNULL(AVG(COMM), 0) AS '커미션의 평균'
FROM emp
GROUP BY DEPTNO
ORDER BY SUM(SAL) DESC;

-- 9번 문제
SELECT EMPNO, ENAME, HIREDATE, SAL, DEPTNO, 
(SELECT DNAME FROM dept WHERE dept.DEPTNO = emp.DEPTNO) AS DNAME
FROM emp
WHERE DEPTNO = (SELECT DEPTNO FROM dept WHERE DNAME = '인사부');

-- 10번 문제
SELECT EMPNO, ENAME, HIREDATE, SAL, e.DEPTNO, d.DNAME
FROM emp e, dept d
WHERE d.DNAME != '인사부'
AND d.DEPTNO = e.DEPTNO
AND SAL >= 500
ORDER BY EMPNO DESC;

